language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=Django==1.4.1
  - DJANGO=Django==1.5
  - DJANGO=Django==1.6
  - DJANGO=Django==1.7
  - DJANGO=https://github.com/django/django/archive/master.zip
matrix:
  include:
    - python: "3.4"
      env: DJANGO=Django==1.5
    - python: "3.4"
      env: DJANGO=Django==1.6
    - python: "3.4"
      env: DJANGO=Django==1.7
    - python: "3.4"
      env: DJANGO=https://github.com/django/django/archive/master.zip
  exclude:
    - python: "2.6"
      env: DJANGO=https://github.com/django/django/archive/master.zip
    - python: "2.6"
      env: DJANGO=Django==1.7
install:
  - if [ $DJANGO = 'Django==1.4.1' -o $DJANGO = 'Django==1.5' -o $DJANGO = 'Django==1.6' ]; then pip install south; fi
  - pip install $DJANGO
  - pip install -e .
script:
  - ./runtests.sh
